package_assets: off
template_function: _.template
javascripts:
  app:
    - public/javascripts/jquery-1.4.4.min.js
    - public/javascripts/json2.js
    - public/javascripts/underscore-1.1.4.js
    - public/javascripts/backbone.js
    - public/javascripts/models/*.js
    - public/javascripts/collections/*.js
    - public/javascripts/views/*.js
    - public/javascripts/application.js
    - public/javascripts/**/*.js
    - app/views/**/*.jst

stylesheets:
  app:
    - public/stylesheets/*.css
